name: Auto Assign

on:
  pull_request:
  workflow_dispatch:

jobs:
  assign:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: gh pr edit "${GITHUB_HEAD_REF}" --add-reviewer cidkumagai
